source: /milenij-documentation/
paths:
  uploads: uploads
  static: ''
collections_config:
  docs:
    path: docs
    glob: []
    icon: docs
    disable_url: false
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Zagreb
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
