site_name: Milenij Upute
site_url: http://help.milenij.hr
copyright: "Copyright &copy; 2025. Milenij d.o.o. - Sva prava pridržana. | Verzija: GIT_HASH"


hooks:
  - hooks/hooks.py
theme:
  name: material
  custom_dir: overrides
  language: hr # Change to 'hr' for Croatian if needed
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.instant # Makes clicking links feel instant
    - navigation.instant.prefetch
    - navigation.instant.progress   
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight 
  palette:
  - media: "(prefers-color-scheme: light)" 
    scheme: default
    primary: "#5279af" # Change this to match your brand color
    accent: orange
    toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate   # 'slate' is the name of the dark theme
    primary: black 
    accent: "#5279af"
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - tags:
      tags_file: system/tags.md
  - awesome-pages
  
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://milenij.hr
      name: Naša web stranica
    - icon: fontawesome/solid/envelope
      link: mailto:support@milenij.hr
      name: Kontaktirajte nas
  generator: false