site_name: Milenij Dokumentacija
site_url: https://matijamurk.github.io/milenij-dokumentacija/
theme:
  name: material
  language: en # Change to 'hr' for Croatian if needed
  features:
    - navigation.instant # Makes clicking links feel instant
    - navigation.expand   # Adds the arrow icon to expand/collapse
    - navigation.indexes
    - search.suggest # Smart search suggestions
    - search.highlight # Highlights search results
  palette:
  - media: "(prefers-color-scheme: light)" 
    scheme: default
    primary: 1E6FA7 # Change this to match your brand color
    accent: 74C2E6
    toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate   # 'slate' is the name of the dark theme
    primary: black 
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
  - search # Enables the search bar
