site_name: Milenij Dokumentacija
site_url: https://matijamurk.github.io/milenij-dokumentacija/
theme:
  name: material
  language: en # Change to 'hr' for Croatian if needed
  features:
    - navigation.instant # Makes clicking links feel instant
    - navigation.sections # Turns top-level folders into bold sections
    - navigation.expand   # Adds the arrow icon to expand/collapse
    - navigation.indexes
    - search.suggest # Smart search suggestions
    - search.highlight # Highlights search results
  palette: 
    primary: indigo # Change this to match your brand color
    accent: blue

plugins:
  - search # Enables the search bar
